# docker-compose.yml
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./.env:/app/.env
    environment:
      - DEBUG=true
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      - api
    ports:
      - "4040:4040"
    volumes:
      - ./.env:/app/.env
    command: http --domain=your-domain-here.ngrok-free.app api:8000 --log stdout
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN} 